# Generated by Django 3.2.4 on 2021-08-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abc', models.ImageField(upload_to='media')),
            ],
        ),
    ]
