# Generated by Django 3.2.4 on 2021-08-18 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_carted1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='carted',
        ),
    ]
