# Generated by Django 3.2.4 on 2021-09-05 06:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0012_auto_20210904_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='cinema_hall',
            fields=[
                ('hname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('pin', models.IntegerField()),
                ('contact', models.BigIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='mov_ticket',
            name='utm',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 5, 12, 26, 25, 422191)),
        ),
        migrations.CreateModel(
            name='select_hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.cinema_hall')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.mov_ticket')),
            ],
        ),
    ]
