# Generated by Django 3.2.4 on 2021-09-09 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0013_auto_20210905_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='calle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ab', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='mov_ticket',
            name='utm',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 9, 14, 44, 9, 481443)),
        ),
    ]
